### ISSUE TITLE
hotkeys do not work with dvorak

### ISSUE THREAD

**Issue by skucherenko** [ai/keyux#12] opened 2024-02-28 16:18 UTC
Looking at the demo page, pressing Option + B (the counter should be bumped) -- nothing happens. Pressing Option + X (it'd correspond to Option + B if I'd use QWERTY and not Dvorak) -- everything works.

Expected: it says Option + B, I press Option + B, it just works
Real: Press Option + B, nothing happens. Frustrating 🤷‍♂️

**Comment by ai** [comment] 2024-02-28 16:23
What `event.key` and `event.code` do you have on `B`/`X` presses?

What OS do you use and how did you enable Dvorak there?

**Comment by skucherenko** [comment] 2024-02-28 16:40
Just 'B':

{
 "key": "x",
 "keyCode": 88,
 "which": 88,
 "code": "KeyB",
 "location": 0,
 "altKey": false,
 "ctrlKey": false,
 "metaKey": false,
 "shiftKey": false,
 "repeat": false
}

Option+B:

{
 "key": "≈",
 "keyCode": 88,
 "which": 88,
 "code": "KeyB",
 "location": 0,
 "altKey": true,
 "ctrlKey": false,
 "metaKey": false,
 "shiftKey": false,
 "repeat": false
}

macOS Sonoma 14.2.1

Dvorak is set up in a standard macOS way.

<img width="224" alt="image" src="https://github.com/ai/keyux/assets/17199375/af03c8fd-f201-4437-b451-712805663cef">


Karabiner-Elements is installed but it has only simple remappings for external keyboards, nothing that should affect this one.

**Comment by skucherenko** [comment] 2024-02-28 16:46
> Can you try to remove [this like](https://github.com/ai/keyux/blob/main/hotkey.js#L40C5-L40C23) and check again?
> 
> > Just 'B':
> 
> Is it Dvorak’s B?

Sorry, here it goes:

Dvorak B, QWERTY N:

{
 "key": "b",
 "keyCode": 66,
 "which": 66,
 "code": "KeyN",
 "location": 0,
 "altKey": false,
 "ctrlKey": false,
 "metaKey": false,
 "shiftKey": false,
 "repeat": false
}

Dvorak X, QWERTY B
{
 "key": "x",
 "keyCode": 88,
 "which": 88,
 "code": "KeyB",
 "location": 0,
 "altKey": false,
 "ctrlKey": false,
 "metaKey": false,
 "shiftKey": false,
 "repeat": false
}

**Comment by skucherenko** [comment] 2024-02-28 16:58
> Can you try to remove [this like](https://github.com/ai/keyux/blob/main/hotkey.js#L40C5-L40C23) and check again?

not sure I understood correctly. Removed `NON_ENGLISH_LAYOUT.test(event.key) &&` check, started locally (pnpm i && pnpm start) -- no luck

**Comment by ai** [comment] 2024-02-28 17:00
> Dvorak B, "key": "b",

Seems like it is not a problem with Dvorak.

Does those <kbd>h</kbd> hotkeys in [demo](https://ai.github.io/keyux/) works in Dvorak (when you press Dvorak’s `h`)?

**Comment by skucherenko** [comment] 2024-02-28 17:22
> > Dvorak B, "key": "b",
> 
> Seems like it is not a problem with Dvorak.
> 
> Does those h hotkeys in [demo](https://ai.github.io/keyux/) works in Dvorak (when you press Dvorak’s `h`)?

Consecutively pressing 'h' in Dvorak and switching tabs with mouse. Looks like expected behavior:

![Screen Recording 2024-02-28 at 21 18 20](https://github.com/ai/keyux/assets/17199375/56040cfb-9716-401b-8b79-9041f9ba3fc0)

**Comment by ai** [comment] 2024-02-28 18:29
Hm. Seems like the problem is with `Option+B`.

1. Can you show Dvorak’s `Option+B` event object?
2. Can you debug those lines to find out why `event.code` was not used? https://github.com/ai/keyux/blob/main/hotkey.js#L37-L45

**Comment by ai** [comment] 2024-10-25 18:13
Closing since it is rare case and reporter do not respond. We will open it later when we have a real use case.

**Closed by ai** 2024-10-25 18:13 UTC
